// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANEKeLRbd3Htk2zEeNsftEfueIYSlf19E',
    appId: '1:457868997288:web:f88101b34b77934e05089d',
    messagingSenderId: '457868997288',
    projectId: 'blabchat',
    authDomain: 'blabchat.firebaseapp.com',
    storageBucket: 'blabchat.firebasestorage.app',
    measurementId: 'G-8FB01HRGB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYmZHrRnTZHkJ9MenZeP7esz9eIVBteHw',
    appId: '1:457868997288:android:645dd127fb6d4e1e05089d',
    messagingSenderId: '457868997288',
    projectId: 'blabchat',
    storageBucket: 'blabchat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmZazYIHei83RhetgDH0G7rxVDBTkBPkM',
    appId: '1:457868997288:ios:00cc415b5255072a05089d',
    messagingSenderId: '457868997288',
    projectId: 'blabchat',
    storageBucket: 'blabchat.firebasestorage.app',
    iosBundleId: 'com.example.blabChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmZazYIHei83RhetgDH0G7rxVDBTkBPkM',
    appId: '1:457868997288:ios:00cc415b5255072a05089d',
    messagingSenderId: '457868997288',
    projectId: 'blabchat',
    storageBucket: 'blabchat.firebasestorage.app',
    iosBundleId: 'com.example.blabChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANEKeLRbd3Htk2zEeNsftEfueIYSlf19E',
    appId: '1:457868997288:web:6659380893c0f35a05089d',
    messagingSenderId: '457868997288',
    projectId: 'blabchat',
    authDomain: 'blabchat.firebaseapp.com',
    storageBucket: 'blabchat.firebasestorage.app',
    measurementId: 'G-ELGTWHBD7W',
  );
}
